### ISSUE TITLE
centos7 安装问题

### ISSUE THREAD

**Issue by sageskr** [idcos/osinstall#1]
PS:安装流程上osinstall与 osinstall-doc中描述不一致。
1、os-install-server安装完成以后，报错：not a valid logrus Level: ""
2、npm(目前为线上最新版本：4.2.4)安装完bower和ember-cli。在ui中执行npm install中报错如下：
[我实在太挫，不太懂nodejs]

npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

> spawn-sync@1.0.15 postinstall /home/worker/idcos/osinstall-ui/node_modules/ember-cli-font-awesome/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

module.js:340
    throw err;
    ^

Error: Cannot find module '/home/worker/idcos/osinstall-ui/node_modules/ember-cli-font-awesome/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
npm ERR! Linux 3.10.0-229.14.1.el7.x86_64
npm ERR! argv "/usr/local/nodejs/bin/node" "/usr/local/nodejs/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/worker/idcos/osinstall-ui/npm-debug.log

**Comment by microsea** [comment]
很多npm包要手工 npm -g xxx来安装，安装后chrome浏览器可显示，遨游无法显示，一片空白。
另设备型号管理 中的各个RAID、OOB、BIOS脚本在哪里找，在github中未找到。

**Comment by yunji-devin** [comment]
hi,@sageskr

1、os-install-server安装完成以后，报错：not a valid logrus Level: ""
这个是正常提示，看起来server已经开始工作了

2.centos7下您可以使用yum 安装nodejs: http://www.jianshu.com/p/783906f10d58
然后接着安装ember-cli

```
npm install -g ember-cli
npm install -g bower

cd /usr/yunji
git clone https://github.com/idcos/osinstall-ui.git
cd /usr/yunji/osinstall-ui/
npm install
bower install
ember server --proxy=http://localhost:8083/
```

**Comment by yunji-devin** [comment]
hi,@microsea，
1.您可以通过以下命令安装依赖包：
npm install -g ember-cli
npm install -g bower

2.您能否将遨游浏览器的开发者模式打开，把console的错误输出发我看看？

3.硬件配置相关的脚本我们这两天会尽快开源出来

**Comment by yunji-devin** [comment]
to all:
我们会尽快放出编译之后的版本，大家直接使用就可以了，不用折腾编译过程中的问题了

**Comment by microsea** [comment]
谢谢您的答复。遨游浏览器的错误截图如下：

2016-01-08 

microsea 

发件人：yunji-devin notifications@github.com
发送时间：2016-01-08 11:38
主题：Re: [osinstall] centos7 安装问题 (#1)
收件人："idcos/osinstall"osinstall@noreply.github.com
抄送："microsea"microsea@126.com

hi,@microsea，
1.您可以通过以下命令安装依赖包：
npm install -g ember-cli
npm install -g bower
2.您能否将遨游浏览器的开发者模式打开，把console的错误输出发我看看？
3.硬件配置相关的脚本我们这两天会尽快开源出来

**Comment by yunji-devin** [comment]
不好意思，您的截图我这边看不到呢
