### ISSUE TITLE
ui启动报错

### ISSUE THREAD

**Issue by zjcnew** [idcos/osinstall#17]
[root@CentOS7 osinstall-ui]# ember server --proxy=http://localhost:8083/
module.js:538
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (/data/app/osinstall-ui/node_modules/ember-cli/node_modules/configstore/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
[root@CentOS7 osinstall-ui]#

**Comment by xibolun** [comment]
```
rm -rf  node_modules
yarn install

```

请不要使用npm进行安装，nvm我没有试过

**Comment by ygmpkk** [comment]
> l

建议你加个issue template

**Comment by champly** [comment]
> ```
> rm -rf  node_modules
> yarn install
> ```
> 
> 请不要使用NPM进行安装，NVM我没有试过

删除了node_modules然后yarn install之后还是一样的错误
但是我把ember-cli从1.13.8升级到1.13.15之后编译能通过，但是项目有很多问题，你是怎么使用1.13.8编译通过的呢？

**Comment by xibolun** [comment]
> > ```
> > rm -rf  node_modules
> > yarn install
> > ```
> > 
> > 
> > 请不要使用NPM进行安装，NVM我没有试过
> 
> 删除了node_modules然后yarn install之后还是一样的错误
> 但是我把ember-cli从1.13.8升级到1.13.15之后编译能通过，但是项目有很多问题，你是怎么使用1.13.8编译通过的呢？

这个项目比较老，我正在考虑使用react重构，后续会发布出来；
我的node版本使用6.9.x, ember-cli 3.7.1

**Comment by wanlxy1111** [comment]
Build error
ui/dashboard/controller.js (in D:\osinstall-ui\tmp\babel-input_base_path-1DLWYfp3.tmp)

ui/dashboard/controller.js: Unexpected token (90:3)

怎么回事啊，根本起不来
